#!/bin/sh
# moopatch
# Uploads a changed file to the MOO server.
# $Source: /cvsroot/stellation/stellation/moopatch,v $
# $State: Exp $
SERVER="pyanfar 7777"
PASSWORD="defaultadminpassword"

tmp=/tmp/moopatch.$$

while [ X$1 != X ]; do
	rm -f $tmp
	echo $PASSWORD > $tmp
	cat $1 >> $tmp
	nc $SERVER < $tmp
	shift
done

# Revision History
# $Log: moopatch,v $
# Revision 1.5  2000/08/01 22:06:04  dtrg
# Owned stars are now showed in yellow again.
# Fixed viewing other people's units; all the tracebacks should have gone.
# Various minor bug fixes and formatting changes.
#
# Revision 1.4  2000/07/31 23:50:16  dtrg
# First interim checkin of the new indirected map code.
#
# Revision 1.3  2000/07/31 18:07:42  dtrg
# Map no longer displays deep space objects (which means it works with
# Netscape again).
# Added maximum number of players feature.
# A few formatting fixes.
#
# Revision 1.2  2000/07/30 21:20:19  dtrg
# Updated all the .patch lines to contain the correct line numbers.
# Cosmetic makeover; we should now hopefully look marginally better.
# Bit more work on the nova cannon.
# A few minor bug fixes.
#
# Revision 1.1.1.1  2000/07/29 17:53:01  dtrg
# Initial checkin.
#

