#!/bin/sh
# moopatch
# Uploads a changed file to the MOO server.
# $Source: /cvsroot/stellation/stellation/moopatch,v $
# $State: Exp $
SERVER="pyanfar 7777"
PASSWORD="omnipotence"

tmp=/tmp/moopatch.$$

while [ X$1 != X ]; do
	rm -f $tmp
	echo $PASSWORD > $tmp
	cat $1 >> $tmp
	nc $SERVER < $tmp
	shift
done

# Revision History
# $Log: moopatch,v $
# Revision 1.2  2000/07/30 21:20:19  dtrg
# Updated all the .patch lines to contain the correct line numbers.
# Cosmetic makeover; we should now hopefully look marginally better.
# Bit more work on the nova cannon.
# A few minor bug fixes.
#
# Revision 1.1.1.1  2000/07/29 17:53:01  dtrg
# Initial checkin.
#

