name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: sudo add-apt-repository ppa:haxe/releases -y && apt update && sudo apt install haxe sassc gpp
    - name: make
      run: make

